//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Blupi.rc
//
#define TX_ACTION_GO                    1
#define TX_ACTION_STOP                  2
#define TX_ACTION_MANGE                 3
#define TX_ACTION_CARRY                 4
#define TX_ACTION_DEPOSE                5
#define TX_ACTION_ABAT                  6
#define TX_ACTION_ROC                   7
#define TX_ACTION_CULTIVE               8
#define TX_ACTION_BUILD1                9
#define TX_ACTION_BUILD2                10
#define TX_ACTION_BUILD3                11
#define TX_ACTION_BUILD4                12
#define TX_ACTION_BUILD5                13
#define TX_ACTION_BUILD6                14
#define TX_ACTION_MUR                   15
#define TX_ACTION_PALIS                 16
#define TX_ACTION_ABATn                 17
#define TX_ACTION_ROCn                  18
#define TX_ACTION_PONT                  19
#define TX_ACTION_TOUR                  20
#define TX_ACTION_BOIT                  21
#define TX_ACTION_LABO                  22
#define TX_ACTION_FLEUR                 23
#define TX_ACTION_FLEURn                24
#define TX_ACTION_DYNAMITE              25
#define TX_ACTION_BATEAU                26
#define TX_ACTION_DJEEP                 27
#define TX_ACTION_DRAPEAU               28
#define TX_ACTION_EXTRAIT               29
#define TX_ACTION_FABJEEP               30
#define TX_ACTION_FABMINE               31
#define TX_ACTION_FABDISC               32
#define TX_ACTION_REPEAT                33
#define TX_ACTION_QARMURE               34
#define TX_ACTION_FABARMURE             35
#define TX_IONAMEEX						100
#define TX_IOFREE						101
#define TX_OWNMISSION					102
#define TX_TESTMISSION					103
#define TX_BUTTON_JOUER					104
#define TX_BUTTON_APPRENDRE				105
#define TX_BUTTON_QUITTER				106
#define TX_BUTTON_PREVP					107
#define TX_BUTTON_NEXTP					108
#define TX_BUTTON_PLAYP					109
#define TX_BUTTON_BUILDP				110
#define TX_BUTTON_TERM					111
#define TX_BUTTON_READP					112
#define TX_BUTTON_WRITEP				113
#define TX_BUTTON_CANCELP				114
#define TX_BUTTON_CONTP					115
#define TX_BUTTON_REPEAT				116
#define TX_CHOOSEPLAYER					117
#define TX_PLAYERSNAME					118
#define TX_BUTTON_TERMC					119
#define TX_CHOOSESIZE					120
#define TX_BUTTON_HVSCROLL				121
#define TX_BUTTON_ONLYHSCROLL			122
#define TX_BUTTON_ONLYVSCROLL			123
#define TX_BUTTON_TESTMISSION			124
#define TX_PAUSE						125
#define TX_CLEARPLAYER					127
#define TX_SETTINGS						128
#define TX_BUTTON_SETUP1				130
#define TX_BUTTON_SETUP2				131
#define TX_BUTTON_SETUP3				132
#define TX_BUTTON_SETUP4				133
#define TX_BUTTON_REGION				144
#define TX_DISCARDGAME					145
#define TX_DESIGNMISSION				147
#define TX_CHOOSEGAMER					148
#define TX_MUSIC						149
#define TX_BUTTON_SETUP5				154
#define TX_BUTTON_SETUP6				155
#define TX_BUTTON_SETUP7				156
#define TX_BUTTON_SETUP8				157
#define TX_READINFO						167
#define TX_CONFIRM						174
#define TX_CANCEL						175
#define TX_YES							176
#define TX_NO							177
#define TX_REGION						178
#define TX_BUTTON_SETUP					180
#define TX_INSERT						182
#define TX_DELETEMISSION				184
#define TX_NONAME						187
#define TX_DESIGN						188
#define TX_MISSIONNUM					189
#define TX_SINGLEPLAYER					195
#define TX_MUTLIPLAYER					196
#define TX_GAMEPAUSE					197
#define TX_FULL_END1					203
#define TX_FULL_END2					204
#define TX_FULL_END3					205
#define TX_FULL_END4					206
#define TX_BUTTON_SKILL					209
#define TX_BUTTON_DEMO					212
#define TX_DEMOREC						213
#define TX_DEMOPLAY						214
#define TX_SHOWNEXT						241
#define TX_SHOWCONNECTION				242
#define TX_SHOWNEXT						245
#define TX_SHOWPREV						246
#define TX_GAMEJOIN						247
#define TX_CREATE_MULTIGAME				248
#define TX_UPDATELIST					249
#define TX_MULTI_CREATE					250
#define TX_MULTI_GNAME					251
#define TX_OPEN							264
#define TX_LOAD_CGAME					269
#define TX_SAVE_CGAME					270
#define TX_GAMESAVED					288
#define TX_NOTINDEMO					289

#define TX_REPEAT_CULTIVE               500
#define TX_REPEAT_FLEUR                 501
#define TX_REPEAT_FLEURQ                502
#define TX_REPEAT_FABMINE               503
#define TX_REPEAT_FABJEEP               504
#define TX_REPEAT_PALIS                 505
#define TX_REPEAT_PALISQ                506
#define TX_REPEAT_PONT                  507
#define TX_REPEAT_PONTQ                 508
#define TX_REPEAT_BATEAU                509
#define TX_REPEAT_BATEAUQ               510
#define TX_REPEAT_FABARMURE             511
#define TX_DIRECT_N                     512
#define TX_DIRECT_S                     513
#define TX_DIRECT_E                     514
#define TX_DIRECT_O                     515
#define IDR_WAVE_BOING                  1000
#define TX_ERROR_MISC                   1000
#define IDR_WAVE_BLOW                   1001
#define TX_ERROR_GROUND                 1001
#define TX_ERROR_FREE                   1002
#define TX_ERROR_PONTOP                 1003
#define TX_ERROR_PONTTERM               1004
#define TX_ERROR_TOURISOL               1005
#define TX_ERROR_TOUREAU                1006
#define TX_ERROR_TELE2                  1007
#define TX_OBJ_BLUPIm                   2000
#define TX_OBJ_BLUPIf                   2001
#define TX_OBJ_BLUPI                    2002
#define TX_OBJ_BATEAU                   2003
#define TX_OBJ_JEEP                     2004
#define TX_OBJ_PIEGE                    2005
#define TX_OBJ_POISON                   2006
#define TX_OBJ_DYNAMITE                 2007
#define TX_OBJ_MINE                     2008
#define TX_OBJ_TOMATE                   2009
#define TX_OBJ_POTION                   2010
#define TX_OBJ_PLANCHE                  2011
#define TX_OBJ_PIERRE                   2012
#define TX_OBJ_DRAPEAU                  2013
#define TX_OBJ_FER                      2014
#define TX_OBJ_FLEUR1                   2015
#define TX_OBJ_FLEUR2                   2016
#define TX_OBJ_FLEUR3                   2017
#define TX_OBJ_CABANE                   2018
#define TX_OBJ_LABO                     2019
#define TX_OBJ_MINEFER                  2020
#define TX_OBJ_USINE                    2021
#define TX_OBJ_TOUR                     2022
#define TX_OBJ_FEU                      2023
#define TX_OBJ_ROBOT                    2024
#define TX_OBJ_TRACKS                   2025
#define TX_OBJ_BOMBE                    2026
#define TX_OBJ_ARAIGNEE                 2027
#define TX_OBJ_VIRUS                    2028
#define TX_OBJ_ELECTRO                  2029
#define TX_OBJ_ARBRE                    2030
#define TX_OBJ_MUR                      2031
#define TX_OBJ_ARBREb                   2032
#define TX_OBJ_ROC                      2033
#define TX_OBJ_OEUF                     2034
#define TX_OBJ_PALISSADE                2035
#define TX_OBJ_ENNEMIp                  2036
#define TX_OBJ_ENNEMI                   2037
#define TX_OBJ_HERBE                    2038
#define TX_OBJ_MOUSSE                   2039
#define TX_OBJ_TERRE                    2040
#define TX_OBJ_EAU                      2041
#define TX_OBJ_RIVE                     2042
#define TX_OBJ_MIXTE                    2043
#define TX_OBJ_PONT                     2044
#define TX_OBJ_COUVEUSE                 2045
#define TX_OBJ_GLACE                    2046
#define TX_OBJ_MAISON                   2047
#define TX_OBJ_HACHURE                  2048
#define TX_OBJ_MOUSSEb                  2049
#define TX_OBJ_BOUQUET1                 2050
#define TX_OBJ_BOUQUET2                 2051
#define TX_OBJ_BOUQUET3                 2052
#define TX_OBJ_DALLE                    2053
#define TX_OBJ_ENNEMIs                  2054
#define TX_OBJ_DISCIPLE                 2055
#define TX_OBJ_METAL                    2056
#define TX_OBJ_FUSEE                    2057
#define TX_OBJ_TELEPORTE                2058
#define TX_OBJ_ARMURE                   2059
#define TX_OBJ_DALLESPEC                2060
#define TX_OBJ_COUVTELE                 2061
#define TX_OBJ_BATIMENT                 2062
#define TX_OBJ_BATENNEMIS               2063
#define TX_OBJ_MURPAL                   2064
#define TX_OBJ_OBJET                    2065
#define TX_OBJ_ARME                     2066
#define TX_OBJ_VEHICULE                 2067
#define TX_OBJ_STARTFEU                 2068
#define TX_OBJ_DELOBJ                   2069
#define TX_OBJ_DELPERSO                 2070
#define TX_OBJ_DELFEU                   2071
#define TX_OBJ_PLANTE                   2072
#define TX_OBJ_BARENNEMIS               2073
#define TX_WIN1                         3000
#define TX_WIN2                         3001
#define TX_WIN3                         3002
#define TX_WIN4                         3003
#define TX_WIN5                         3004
#define TX_LOST1                        3100
#define TX_LOST2                        3101
#define TX_LOST3                        3102
#define TX_LOST4                        3103
#define TX_LOST5                        3104
#define TX_LASTWIN1                     3200
#define TX_LASTWIN2                     3201
#define TX_LASTWIN3                     3202
#define IDM_EXIT                        40001
#define TX_BUTTON_CREATE	6900

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
